import { describe, expect, it, vi } from 'vitest';
import {
  decodePLYPackedRGB,
  parsePLY,
  parsePLYHeader,
  plyTypeSize,
  readPLYValue,
} from '../src/parsers/plyParser';

const encoder = new TextEncoder();

function bytes(text: string): Uint8Array {
  return encoder.encode(text);
}

function concatBytes(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.byteLength, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.byteLength;
  }
  return out;
}

describe('plyParser helpers', () => {
  it('returns byte sizes for supported PLY scalar types', () => {
    expect(plyTypeSize('char')).toBe(1);
    expect(plyTypeSize('uchar')).toBe(1);
    expect(plyTypeSize('short')).toBe(2);
    expect(plyTypeSize('ushort')).toBe(2);
    expect(plyTypeSize('int')).toBe(4);
    expect(plyTypeSize('uint')).toBe(4);
    expect(plyTypeSize('float')).toBe(4);
    expect(plyTypeSize('double')).toBe(8);
    expect(plyTypeSize('unknown')).toBe(4);
  });

  it('reads all supported PLY scalar value types', () => {
    const buffer = new ArrayBuffer(64);
    const view = new DataView(buffer);
    view.setInt8(0, -1);
    view.setUint8(1, 255);
    view.setInt16(2, -123, true);
    view.setUint16(4, 456, true);
    view.setInt32(8, -789, true);
    view.setUint32(12, 987, true);
    view.setFloat32(16, 1.5, true);
    view.setFloat64(24, 2.5, true);
    view.setFloat32(40, 3.5, true);

    expect(readPLYValue(view, 0, 'char', true)).toBe(-1);
    expect(readPLYValue(view, 1, 'uchar', true)).toBe(255);
    expect(readPLYValue(view, 2, 'short', true)).toBe(-123);
    expect(readPLYValue(view, 4, 'ushort', true)).toBe(456);
    expect(readPLYValue(view, 8, 'int', true)).toBe(-789);
    expect(readPLYValue(view, 12, 'uint', true)).toBe(987);
    expect(readPLYValue(view, 16, 'float', true)).toBe(1.5);
    expect(readPLYValue(view, 24, 'double', true)).toBe(2.5);
    expect(readPLYValue(view, 40, 'unknown', true)).toBe(3.5);
  });

  it('decodes integer and float-packed RGB values', () => {
    const buffer = new ArrayBuffer(4);
    const view = new DataView(buffer);
    view.setUint32(0, 0x112233, true);

    expect(decodePLYPackedRGB(0x112233, 'uint')).toBe(0x112233);
    expect(decodePLYPackedRGB(-3.9, 'int')).toBe(0);
    expect(decodePLYPackedRGB(view.getFloat32(0, true), 'float')).toBe(0x112233);
  });
});

describe('parsePLYHeader', () => {
  it('parses header properties and ignores comments and list properties', () => {
    const header = parsePLYHeader(bytes([
      'ply',
      'format ascii 1.0',
      'comment generated by test',
      'element vertex 2',
      'property float x',
      'property float y',
      'property float z',
      'property list uchar int vertex_indices',
      'element face 0',
      'end_header',
      '0 0 0',
    ].join('\n') + '\n'));

    expect(header.format).toBe('ascii');
    expect(header.vertexCount).toBe(2);
    expect(header.vertexProps.map(prop => prop.name)).toEqual(['x', 'y', 'z']);
    expect(header.propIndex).toEqual({ x: 0, y: 1, z: 2 });
  });

  it('rejects invalid PLY headers', () => {
    expect(() => parsePLYHeader(bytes('ply\nformat ascii 1.0\n'))).toThrow('missing end_header');
    expect(() => parsePLYHeader(bytes('ply\nformat ascii 1.0\nend_header'))).toThrow('malformed end_header');
    expect(() => parsePLYHeader(bytes('not_ply\nformat ascii 1.0\nend_header\n'))).toThrow('Not a PLY file');
  });
});

describe('parsePLY', () => {
  it('parses ASCII vertices with normalized float intensity and RGB colors', () => {
    const warn = vi.spyOn(console, 'log').mockImplementation(() => {});
    const data = bytes([
      'ply',
      'format ascii 1.0',
      'element vertex 2',
      'property float x',
      'property float y',
      'property float z',
      'property float intensity',
      'property uchar red',
      'property uchar green',
      'property uchar blue',
      'end_header',
      '1 2 3 0.5 10 20 30',
      '4 5 6 1.0 40 50 60',
    ].join('\n') + '\n');

    const parsed = parsePLY(data, 10);

    expect(Array.from(parsed.positions)).toEqual([1, 2, 3, 4, 5, 6]);
    expect(Array.from(parsed.values)).toEqual([128, 255]);
    expect(Array.from(parsed.rgb!)).toEqual([10, 20, 30, 40, 50, 60]);
    warn.mockRestore();
  });

  it('parses ASCII packed RGB and samples by maxPoints', () => {
    const log = vi.spyOn(console, 'log').mockImplementation(() => {});
    const data = bytes([
      'ply',
      'format ascii 1.0',
      'element vertex 4',
      'property float x',
      'property float y',
      'property float z',
      'property uint rgb',
      'end_header',
      '0 1 2 66051',
      '3 4 5 263430',
      '6 7 8 460809',
      '9 10 11 658188',
    ].join('\n') + '\n');

    const parsed = parsePLY(data, 2);

    expect(Array.from(parsed.positions)).toEqual([0, 1, 2, 6, 7, 8]);
    expect(Array.from(parsed.values)).toEqual([2, 8]);
    expect(Array.from(parsed.rgb!)).toEqual([1, 2, 3, 7, 8, 9]);
    log.mockRestore();
  });

  it('parses binary little-endian vertices with intensity and RGB colors', () => {
    const log = vi.spyOn(console, 'log').mockImplementation(() => {});
    const header = bytes([
      'ply',
      'format binary_little_endian 1.0',
      'element vertex 2',
      'property float x',
      'property float y',
      'property float z',
      'property ushort intensity',
      'property uchar red',
      'property uchar green',
      'property uchar blue',
      'end_header',
    ].join('\n') + '\n');
    const body = new Uint8Array(17 * 2);
    const view = new DataView(body.buffer);
    [[1, 2, 3, 500, 10, 20, 30], [4, 5, 6, 700, 40, 50, 60]].forEach((row, index) => {
      const base = index * 17;
      view.setFloat32(base, row[0], true);
      view.setFloat32(base + 4, row[1], true);
      view.setFloat32(base + 8, row[2], true);
      view.setUint16(base + 12, row[3], true);
      body[base + 14] = row[4];
      body[base + 15] = row[5];
      body[base + 16] = row[6];
    });

    const parsed = parsePLY(concatBytes(header, body), 10);

    expect(Array.from(parsed.positions)).toEqual([1, 2, 3, 4, 5, 6]);
    expect(Array.from(parsed.values)).toEqual([500, 700]);
    expect(Array.from(parsed.rgb!)).toEqual([10, 20, 30, 40, 50, 60]);
    log.mockRestore();
  });

  it('parses binary big-endian vertices and uses z as fallback value', () => {
    const log = vi.spyOn(console, 'log').mockImplementation(() => {});
    const header = bytes([
      'ply',
      'format binary_big_endian 1.0',
      'element vertex 1',
      'property double x',
      'property double y',
      'property double z',
      'end_header',
    ].join('\n') + '\n');
    const body = new Uint8Array(24);
    const view = new DataView(body.buffer);
    view.setFloat64(0, 1.5, false);
    view.setFloat64(8, 2.5, false);
    view.setFloat64(16, 3.5, false);

    const parsed = parsePLY(concatBytes(header, body), 10);

    expect(Array.from(parsed.positions)).toEqual([1.5, 2.5, 3.5]);
    expect(Array.from(parsed.values)).toEqual([3.5]);
    expect(parsed.rgb).toBeUndefined();
    log.mockRestore();
  });

  it('rejects PLY files without x/y/z vertex properties', () => {
    const data = bytes([
      'ply',
      'format ascii 1.0',
      'element vertex 1',
      'property float x',
      'property float y',
      'end_header',
      '1 2',
    ].join('\n') + '\n');

    expect(() => parsePLY(data, 10)).toThrow('PLY missing x/y/z properties');
  });
});