/// <reference types="node" />

import { Locator, Page, expect } from '@playwright/test';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// From q3dweb/test/e2e → web_q3d workspace root.
export const REPO_ROOT = path.resolve(__dirname, '../../..');
// Minimal, self-contained test fixtures generated by testdata/generate.py.
export const TESTDATA_DIR = path.resolve(__dirname, 'testdata');
export const SAMPLE_PCD = path.resolve(TESTDATA_DIR, 'tiny_ascii.pcd');

/** Read any generated fixture file under test/e2e/testdata/ as bytes. */
export function readTestData(fileName: string): Uint8Array {
  return new Uint8Array(fs.readFileSync(path.resolve(TESTDATA_DIR, fileName)));
}

/**
 * Drop a file onto the #app container by constructing a File in the page context
 * and dispatching dragenter / dragover / drop events with a real DataTransfer.
 */
export async function dropFile(page: Page, fileName: string, bytes: Uint8Array): Promise<void> {
  const b64 = Buffer.from(bytes).toString('base64');
  await page.evaluate(
    async ({ name, b64 }) => {
      const bin = atob(b64);
      const buf = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
      const file = new File([buf], name, { type: 'application/octet-stream' });
      const dt = new DataTransfer();
      dt.items.add(file);
      const target = document.getElementById('app')!;
      const opts: DragEventInit = { bubbles: true, cancelable: true, dataTransfer: dt };
      target.dispatchEvent(new DragEvent('dragenter', opts));
      target.dispatchEvent(new DragEvent('dragover', opts));
      target.dispatchEvent(new DragEvent('drop', opts));
    },
    { name: fileName, b64 },
  );
}

export function readSamplePCD(): Uint8Array {
  return new Uint8Array(fs.readFileSync(SAMPLE_PCD));
}

/** Number of points in every generated fixture under test/e2e/testdata/. */
export const TESTDATA_POINT_COUNT = 1024;

/** Build a minimal ASCII PLY with N random points for tests that do not need the large sample. */
export function makeAsciiPLY(count = 1000): Uint8Array {
  const header = [
    'ply',
    'format ascii 1.0',
    `element vertex ${count}`,
    'property float x',
    'property float y',
    'property float z',
    'end_header',
    '',
  ].join('\n');
  const lines: string[] = [header];
  for (let i = 0; i < count; i++) {
    const x = (Math.sin(i) * 5).toFixed(4);
    const y = (Math.cos(i) * 5).toFixed(4);
    const z = ((i % 100) * 0.1).toFixed(4);
    lines.push(`${x} ${y} ${z}`);
  }
  return new TextEncoder().encode(lines.join('\n') + '\n');
}

/** Wait until the loaded point-count label appears in the settings panel. */
export async function waitForPointCount(page: Page, timeout = 30_000): Promise<string> {
  const locator = page.locator('text=/\\d[\\d,]*\\s*pts/').first();
  await expect(locator).toBeVisible({ timeout });
  return (await locator.textContent()) ?? '';
}

/** Sniff all console errors and uncaught page errors during the current test. */
export function attachErrorSinks(page: Page) {
  const consoleErrors: string[] = [];
  const pageErrors: string[] = [];
  page.on('console', (msg) => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  });
  page.on('pageerror', (err) => pageErrors.push(String(err)));
  return { consoleErrors, pageErrors };
}

export function parsePointCount(label: string): number {
  const m = label.match(/([\d,]+)\s*pts/);
  if (!m) return 0;
  return parseInt(m[1].replace(/,/g, ''), 10);
}

/** Locate the CloudItem size label regardless of whether units are shown. */
export function getCloudSizeLabel(page: Page): Locator {
  return page.getByText(/^Size(?: \((?:pixel|cm)\))?:$/).first();
}

/** Locate the CloudItem size input associated with the size label. */
export function getCloudSizeInput(page: Page): Locator {
  return getCloudSizeLabel(page).locator('xpath=following-sibling::input[1]');
}

/** Locate the item/settings select, excluding the viewer-mode selector above it. */
export function getSettingsItemSelect(page: Page): Locator {
  return page.locator('[data-role="settings-item-select"]');
}
